# Generated by Django 2.0.7 on 2018-07-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20180725_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='joiner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='joiners',
            field=models.ManyToManyField(related_name='usersjoiners', to='firstApp.User'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
